import { resolve } from 'node:path';
import { Hono } from 'hono';
import { PROTOCOL_VERSION, type ClientMessage } from '@gosai/shared/protocol';
import type { AppDeviceSettingsPatch } from '@gosai/shared';
import { verifyToken, type TokenScope } from '@gosai/shared/auth';
import { ServerEvents } from '@gosai/shared/events';
import { assertSlug, isValidSlug } from '@gosai/shared/slug';
import type { GosaiPaths } from './paths.js';
import { Logger } from './logger/index.js';
import { EventBus, WebSocketGateway, type ClientData } from './ipc/index.js';
import { AppSettingsStore, ConfigStore } from './config/index.js';
import { bridgeExecutable, DriverManager, SYSTEM_BINDING } from './drivers/index.js';
import {
  applyAppDeviceSettings,
  applyGlobalCameraSettings,
  driverConfigFor,
} from './drivers/camera-config.js';
import { AppManager } from './apps/index.js';
import { AppStorage } from './apps/storage.js';
import { SystemMonitor } from './monitor/index.js';
import { canAccessApp, commandDenial } from './access/policy.js';
import { readBearerToken, RequestGuard } from './access/request-guard.js';
import { resolveStaticFile } from './apps/static-files.js';
import { existsSync } from 'node:fs';

const SERVER_VERSION = '0.1.0';

export interface ServerOptions {
  readonly host: string;
  readonly port: number;
  readonly paths: GosaiPaths;
  readonly pythonDir?: string;
  readonly builtinAppsDir?: string;
  readonly enablePython?: boolean;
  /**
   * Secret generated by desktop main at each launch. It authorizes the
   * dashboard, and app tokens are derived from it.
   */
  readonly dashboardToken: string;
  /** Extra origins allowed besides loopback http origins, e.g. `file://` and `null`. */
  readonly allowedOrigins?: readonly string[];
  /** Extra Host header names allowed besides loopback names and the bind host. */
  readonly allowedHosts?: readonly string[];
  /** Let `app:install` clone `file:` URLs. Only for tests. */
  readonly allowFileInstalls?: boolean;
}

export interface GosaiServer {
  stop(): Promise<void>;
  /** Actual bound port (differs from options.port when 0 was requested). */
  readonly port: number;
  readonly logger: Logger;
  readonly bus: EventBus;
  readonly drivers: DriverManager;
  readonly apps: AppManager;
  readonly monitor: SystemMonitor;
  readonly config: ConfigStore;
  readonly appSettings: AppSettingsStore;
}

export async function createServer(options: ServerOptions): Promise<GosaiServer> {
  const logger = new Logger({ logsDir: options.paths.logs });
  const log = logger.child('server');

  const bus = new EventBus();

  logger.subscribe((entry) => bus.emit(ServerEvents.Log, entry, 'logger'));

  const config = new ConfigStore(options.paths.config, bus, logger.child('config'));
  const appSettings = new AppSettingsStore(options.paths.apps, bus, logger.child('app-config'));

  const pythonDir = resolvePythonDir(options.pythonDir);

  const drivers = new DriverManager({
    pythonDir,
    logger,
    bus,
    getDriverConfig: (binding, driver) => driverConfigFor({ config, appSettings }, binding, driver),
  });

  if (options.enablePython !== false && pythonHasBridge(pythonDir)) {
    try {
      await drivers.start();
    } catch (err) {
      log.warn('failed to start python bridge', { err: String(err) });
    }
  } else {
    log.info('python bridge disabled or unavailable', { pythonDir });
  }

  const apps = new AppManager({
    paths: options.paths,
    logger,
    bus,
    drivers,
    builtinAppsDir: options.builtinAppsDir,
    allowFileInstalls: options.allowFileInstalls === true,
  });
  const storage = new AppStorage(options.paths);

  const monitor = new SystemMonitor({ bus, logger: logger.child('monitor') });
  monitor.start();

  const gateway = new WebSocketGateway(bus, logger.child('ipc'), {
    onClientDisconnect: (clientId) =>
      drivers
        .unsubscribeAll(clientId)
        .catch((err) => log.warn('driver cleanup failed', { clientId, err: String(err) })),
  });
  registerHandlers(gateway, { apps, drivers, config, appSettings, logger, bus });

  let boundPort = options.port;
  const guard = new RequestGuard({
    bindHost: options.host,
    port: () => boundPort,
    ...(options.allowedHosts ? { allowedHosts: options.allowedHosts } : {}),
    ...(options.allowedOrigins ? { allowedOrigins: options.allowedOrigins } : {}),
  });
  const authenticate = (req: Request, token: string | null): TokenScope | null =>
    verifyToken(options.dashboardToken, token ?? readBearerToken(req));

  const app = new Hono<{ Variables: { scope: TokenScope } }>();

  app.use('*', async (c, next) => {
    await next();
    for (const [name, value] of Object.entries(guard.corsHeaders(c.req.raw))) {
      c.header(name, value);
    }
  });
  app.options('*', (c) => c.body(null, 204));

  // Static app files and the SDK bundle load through `import()` and `<img>`,
  // which can't send a token. Every other /v1 route needs one.
  app.use('/v1/*', async (c, next) => {
    if (/^\/v1\/apps\/[^/]+\/static\//.test(c.req.path)) return next();
    const scope = authenticate(c.req.raw, null);
    if (!scope) return c.json({ error: 'unauthorized' }, 401);
    c.set('scope', scope);
    return next();
  });

  app.get('/healthz', (c) => c.json({ ok: true, version: SERVER_VERSION }));
  app.get('/v1/info', (c) =>
    c.json({
      protocolVersion: PROTOCOL_VERSION,
      serverVersion: SERVER_VERSION,
    }),
  );
  app.get('/v1/apps', (c) => c.json({ apps: apps.listApps() }));
  app.get('/v1/drivers', (c) => c.json({ drivers: drivers.listDrivers() }));
  app.get('/v1/experiences', (c) => c.json({ experiences: apps.listRunningExperiences() }));

  app.post('/v1/experiences/start', async (c) => {
    let body: { appSlug?: string; experienceSlug?: string; driverBinding?: string };
    try {
      body = (await c.req.json()) as typeof body;
    } catch {
      return c.json({ error: 'invalid JSON body' }, 400);
    }
    if (!isValidSlug(body.appSlug) || !body.experienceSlug) {
      return c.json({ error: 'appSlug and experienceSlug are required' }, 400);
    }
    if (body.driverBinding !== undefined && !isValidSlug(body.driverBinding)) {
      return c.json({ error: 'invalid driverBinding' }, 400);
    }
    const denial = commandDenial(c.get('scope'), 'experience:start', body);
    if (denial) return c.json({ error: denial }, 403);
    try {
      const running = await apps.startExperience(body.appSlug, body.experienceSlug, {
        driverBinding: body.driverBinding,
      });
      return c.json({ ok: true, experience: running });
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      return c.json({ error: message }, 500);
    }
  });

  app.post('/v1/experiences/stop', async (c) => {
    let body: { appSlug?: string; experienceSlug?: string };
    try {
      body = (await c.req.json()) as typeof body;
    } catch {
      return c.json({ error: 'invalid JSON body' }, 400);
    }
    if (!isValidSlug(body.appSlug) || !body.experienceSlug) {
      return c.json({ error: 'appSlug and experienceSlug are required' }, 400);
    }
    const denial = commandDenial(c.get('scope'), 'experience:stop', body);
    if (denial) return c.json({ error: denial }, 403);
    try {
      await apps.stopExperience(body.appSlug, body.experienceSlug);
      return c.json({ ok: true });
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      return c.json({ error: message }, 500);
    }
  });
  app.get('/v1/config', (c) => c.json(config.get()));
  app.get('/v1/logs', (c) => c.json({ logs: logger.history() }));

  // Per-app storage endpoints used by the SDK StorageClient. App tokens only
  // reach the apps they were minted for.
  app.use('/v1/apps/:slug/storage/*', async (c, next) => {
    const slug = c.req.param('slug');
    if (!isValidSlug(slug)) return c.json({ error: 'invalid app slug' }, 400);
    if (!canAccessApp(c.get('scope'), slug)) return c.json({ error: 'forbidden' }, 403);
    if (!apps.getApp(slug)) return c.json({ error: 'app not found' }, 404);
    return next();
  });
  app.get('/v1/apps/:slug/storage', (c) => {
    const slug = c.req.param('slug');
    return c.json({ keys: storage.list(slug) });
  });
  app.get('/v1/apps/:slug/storage/:key', (c) => {
    const slug = c.req.param('slug');
    const key = c.req.param('key');
    const value = storage.get(slug, key);
    if (value === undefined) return c.json({ error: 'not found' }, 404);
    return c.json(value);
  });
  app.post('/v1/apps/:slug/storage/:key', async (c) => {
    const slug = c.req.param('slug');
    const key = c.req.param('key');
    let body: unknown;
    try {
      body = await c.req.json();
    } catch {
      return c.json({ error: 'invalid JSON body' }, 400);
    }
    storage.set(slug, key, body);
    return c.json({ ok: true });
  });
  app.delete('/v1/apps/:slug/storage/:key', (c) => {
    const slug = c.req.param('slug');
    const key = c.req.param('key');
    const removed = storage.remove(slug, key);
    return c.json({ ok: removed });
  });

  // Static assets for installed apps so the app-host renderer can fetch them
  // directly. resolveStaticFile keeps the resolved path inside the app.
  app.get('/v1/apps/:slug/static/*', async (c) => {
    const slug = c.req.param('slug');
    if (!isValidSlug(slug)) return c.json({ error: 'invalid app slug' }, 400);
    const installed = apps.getApp(slug);
    if (!installed) return c.json({ error: 'app not found' }, 404);
    const prefix = `/v1/apps/${slug}/static/`;
    const pathname = new URL(c.req.url).pathname;
    if (!pathname.startsWith(prefix)) return c.json({ error: 'not found' }, 404);
    let requestPath: string;
    try {
      requestPath = decodeURIComponent(pathname.slice(prefix.length));
    } catch {
      return c.json({ error: 'invalid path' }, 400);
    }
    const filePath = resolveStaticFile(installed.installPath, requestPath);
    if (!filePath) {
      return c.json({ error: 'not found' }, 404);
    }
    const data = await Bun.file(filePath).arrayBuffer();
    const mime = guessMime(filePath);
    return new Response(data, {
      headers: { 'content-type': mime, 'cache-control': 'no-cache' },
    });
  });

  // Bundled SDK runtime served to apps via static script tag.
  app.get('/sdk-runtime.js', async (c) => {
    const sdkPath = process.env.GOSAI_SDK_RUNTIME
      ? resolve(process.env.GOSAI_SDK_RUNTIME)
      : resolve(import.meta.dir, '..', '..', 'sdk', 'dist', 'browser.js');
    if (existsSync(sdkPath)) {
      const data = await Bun.file(sdkPath).arrayBuffer();
      return new Response(data, {
        headers: {
          'content-type': 'application/javascript; charset=utf-8',
          'cache-control': 'no-cache',
        },
      });
    }
    return c.json({ error: 'SDK runtime bundle not built' }, 404);
  });

  let server: ReturnType<typeof Bun.serve<ClientData>>;
  try {
    server = Bun.serve<ClientData>({
      hostname: options.host,
      port: options.port,
      fetch(req, srv) {
        const rejected = guard.reject(req);
        if (rejected) return rejected;
        const url = new URL(req.url);
        if (url.pathname === '/ws') {
          // Browsers can't set headers on a WebSocket, so the token may come
          // in the query string.
          const scope = authenticate(req, url.searchParams.get('token'));
          if (!scope) return new Response('Unauthorized', { status: 401 });
          const data: ClientData = { clientId: crypto.randomUUID(), scope };
          if (srv.upgrade(req, { data })) {
            return undefined;
          }
          return new Response('Upgrade failed', { status: 426 });
        }
        return app.fetch(req);
      },
      websocket: {
        open(ws) {
          gateway.onOpen(ws);
        },
        close(ws) {
          gateway.onClose(ws);
        },
        async message(ws, msg) {
          await gateway.onMessage(ws, msg);
        },
      },
    });
  } catch (err) {
    const message = String((err as Error)?.message ?? err);
    if (message.includes('EADDRINUSE') || message.includes('Address already in use')) {
      log.error('port already in use', { port: options.port, host: options.host });
      throw new Error(
        `GOSAI cannot bind to ${options.host}:${options.port} - the port is already in use. ` +
          'Stop the other process or set GOSAI_PORT to a free port.',
      );
    }
    throw err;
  }

  boundPort = server.port ?? options.port;
  log.info(`gosai server up on http://${options.host}:${boundPort}`);

  return {
    port: boundPort,
    logger,
    bus,
    drivers,
    apps,
    monitor,
    config,
    appSettings,
    async stop() {
      log.info('shutting down');
      monitor.stop();
      gateway.close();
      try {
        await apps.shutdown();
      } catch (err) {
        log.warn('apps shutdown error', { err: String(err) });
      }
      try {
        await drivers.stop();
      } catch (err) {
        log.warn('drivers shutdown error', { err: String(err) });
      }
      server.stop();
    },
  };
}

function registerHandlers(
  gateway: WebSocketGateway,
  ctx: {
    apps: AppManager;
    drivers: DriverManager;
    config: ConfigStore;
    appSettings: AppSettingsStore;
    logger: Logger;
    bus: EventBus;
  },
): void {
  const { apps, drivers, config, appSettings, logger, bus } = ctx;

  gateway.registerHandler('apps:list', () => ({ apps: apps.listApps() }));
  gateway.registerHandler('app:install', async (msg: ClientMessage) => {
    const payload = (msg as { payload: { source?: string } }).payload;
    if (!payload?.source) throw new Error('source is required');
    return await apps.installFromGit(payload.source);
  });
  gateway.registerHandler('app:uninstall', async (msg: ClientMessage) => {
    const payload = (msg as { payload: { slug?: string } }).payload;
    const slug = assertSlug(payload?.slug, 'slug');
    await apps.uninstall(slug);
    return { slug };
  });

  gateway.registerHandler('experiences:list', () => ({
    experiences: apps.listRunningExperiences(),
  }));
  gateway.registerHandler('experience:start', async (msg: ClientMessage) => {
    const payload = (
      msg as { payload: { appSlug?: string; experienceSlug?: string; driverBinding?: string } }
    ).payload;
    const appSlug = assertSlug(payload?.appSlug, 'appSlug');
    if (!payload.experienceSlug) throw new Error('experienceSlug is required');
    const driverBinding =
      payload.driverBinding === undefined
        ? undefined
        : assertSlug(payload.driverBinding, 'driverBinding');
    return await apps.startExperience(appSlug, payload.experienceSlug, { driverBinding });
  });
  gateway.registerHandler('experience:stop', async (msg: ClientMessage) => {
    const payload = (msg as { payload: { appSlug?: string; experienceSlug?: string } }).payload;
    const appSlug = assertSlug(payload?.appSlug, 'appSlug');
    if (!payload.experienceSlug) throw new Error('experienceSlug is required');
    await apps.stopExperience(appSlug, payload.experienceSlug);
    return { ok: true };
  });

  gateway.registerHandler('drivers:list', () => ({ drivers: drivers.listDrivers() }));
  gateway.registerHandler('devices:list', async () => await drivers.listDevices());
  gateway.registerHandler('driver:get-data', async (msg: ClientMessage) => {
    const payload = (msg as { payload: { driver?: string; event?: string; binding?: string } })
      .payload;
    if (!payload?.driver || !payload.event) throw new Error('driver and event are required');
    return await drivers.getData(bindingOf(payload), payload.driver, payload.event);
  });
  gateway.registerHandler('driver:execute', async (msg: ClientMessage) => {
    const payload = (
      msg as { payload: { driver?: string; action?: string; data?: unknown; binding?: string } }
    ).payload;
    if (!payload?.driver || !payload.action) throw new Error('driver and action are required');
    return await drivers.execute(bindingOf(payload), payload.driver, payload.action, payload.data);
  });
  gateway.registerHandler('driver:subscribe', async (msg: ClientMessage, ctx) => {
    const payload = (msg as { payload: { driver?: string; event?: string; binding?: string } })
      .payload;
    if (!payload?.driver || !payload.event) throw new Error('driver and event are required');
    await drivers.subscribe(bindingOf(payload), payload.driver, payload.event, ctx.clientId);
    return { ok: true };
  });
  gateway.registerHandler('driver:unsubscribe', async (msg: ClientMessage, ctx) => {
    const payload = (msg as { payload: { driver?: string; event?: string; binding?: string } })
      .payload;
    if (!payload?.driver || !payload.event) throw new Error('driver and event are required');
    await drivers.unsubscribe(bindingOf(payload), payload.driver, payload.event, ctx.clientId);
    return { ok: true };
  });

  gateway.registerHandler('logs:history', () => ({ logs: logger.history() }));
  gateway.registerHandler('config:get', () => config.get());
  gateway.registerHandler('config:set', async (msg: ClientMessage) => {
    const payload = (msg as { payload: Record<string, unknown> }).payload;
    const previousCamera = config.get().camera;
    const next = config.update(payload);
    await applyGlobalCameraSettings(
      drivers,
      { config, appSettings },
      previousCamera,
      logger.child('camera'),
    );
    return next;
  });

  gateway.registerHandler('app:config:get', (msg: ClientMessage) => {
    const payload = (msg as { payload: { appSlug?: string } }).payload;
    return appSettings.get(assertSlug(payload?.appSlug, 'appSlug'));
  });
  gateway.registerHandler('app:config:set', async (msg: ClientMessage) => {
    const payload = (msg as { payload: { appSlug?: string; settings?: AppDeviceSettingsPatch } })
      .payload;
    const appSlug = assertSlug(payload?.appSlug, 'appSlug');
    const previous = appSettings.get(appSlug);
    const next = appSettings.update(appSlug, payload.settings ?? {});
    await applyAppDeviceSettings(
      drivers,
      { config, appSettings },
      appSlug,
      previous,
      logger.child('app-config'),
    );
    return next;
  });

  // App-scoped pub/sub used by multi-window experiences (e.g. calibration
  // running in projector + control windows). Emits `app:<slug>:<topic>` on
  // the bus; clients subscribed to that event name receive it.
  gateway.registerHandler('app:broadcast', (msg: ClientMessage) => {
    const payload = msg.payload as {
      appSlug?: string;
      topic?: string;
      data?: unknown;
    };
    const appSlug = assertSlug(payload?.appSlug, 'appSlug');
    if (!payload.topic) throw new Error('topic is required');
    bus.emit(`app:${appSlug}:${payload.topic}`, payload.data ?? null, `app:${appSlug}`);
    return { ok: true };
  });

  // App-level log forwarding. Apps using the SDK log via app:log; we re-emit
  // through the central logger so the dashboard shows them inline.
  gateway.registerHandler('app:log', (msg: ClientMessage) => {
    const payload = msg.payload as {
      source?: string;
      level?: 'debug' | 'info' | 'warn' | 'error';
      message?: string;
      data?: Record<string, unknown> | null;
    };
    if (!payload?.source || !payload.message) {
      return { ok: false };
    }
    const level = payload.level ?? 'info';
    logger.log(payload.source, level, payload.message, payload.data ?? undefined);
    return { ok: true };
  });
}

/** The driver binding a command names, defaulting to the dashboard's `system` binding. */
function bindingOf(payload: { binding?: string }): string {
  return payload.binding === undefined ? SYSTEM_BINDING : assertSlug(payload.binding, 'binding');
}

function guessMime(filePath: string): string {
  const lower = filePath.toLowerCase();
  if (lower.endsWith('.html')) return 'text/html; charset=utf-8';
  if (lower.endsWith('.js') || lower.endsWith('.mjs'))
    return 'application/javascript; charset=utf-8';
  if (lower.endsWith('.json')) return 'application/json; charset=utf-8';
  if (lower.endsWith('.css')) return 'text/css; charset=utf-8';
  if (lower.endsWith('.png')) return 'image/png';
  if (lower.endsWith('.jpg') || lower.endsWith('.jpeg')) return 'image/jpeg';
  if (lower.endsWith('.svg')) return 'image/svg+xml';
  if (lower.endsWith('.webp')) return 'image/webp';
  if (lower.endsWith('.ico')) return 'image/x-icon';
  if (lower.endsWith('.txt') || lower.endsWith('.md')) return 'text/plain; charset=utf-8';
  if (lower.endsWith('.wasm')) return 'application/wasm';
  return 'application/octet-stream';
}

function resolvePythonDir(override?: string): string {
  if (override) return resolve(override);
  const env = process.env.GOSAI_PYTHON_DIR;
  if (env) return resolve(env);
  return resolve(import.meta.dir, '..', '..', '..', 'python');
}

function pythonHasBridge(pythonDir: string): boolean {
  return existsSync(bridgeExecutable(pythonDir));
}
