/**
 * Wires the server together: stores, managers, the WebSocket gateway and the
 * HTTP routes. Paths come in through the options; see index.ts.
 */

import { existsSync } from 'node:fs';
import { join } from 'node:path';
import { verifyToken, type TokenScope } from '@gosai/shared/auth';
import { ServerEvents } from '@gosai/shared/events';
import { bridgeExecutable } from '@gosai/shared/python-bridge';
import { grantFor } from './access/capabilities.js';
import { readBearerToken, RequestGuard } from './access/request-guard.js';
import { migrateLegacyAppData } from './apps/data-migration.js';
import { appOriginDenial } from './apps/app-host.js';
import { CalibrationStore } from './apps/calibration.js';
import { AppManager } from './apps/manager.js';
import { AppSettingsValuesStore } from './apps/settings.js';
import { AppStorage } from './apps/storage.js';
import { createCommandHandlers } from './commands/index.js';
import { AppSettingsStore } from './config/app-settings.js';
import { ConfigStore } from './config/config.js';
import type { PythonToolchain } from './apps/python-env.js';
import { pythonAppBridges } from './drivers/app-drivers.js';
import { driverConfigFor } from './drivers/camera-config.js';
import { DriverHub } from './drivers/hub.js';
import { createHttpRoutes } from './http/routes.js';
import { EventBus } from './ipc/bus.js';
import { WebSocketGateway, type ClientData } from './ipc/gateway.js';
import { Logger } from './logger/logger.js';
import { SystemMonitor } from './monitor/monitor.js';
import type { GosaiPaths } from './paths.js';
import { SERVER_VERSION } from './version.js';

export interface ServerOptions {
  readonly host: string;
  readonly port: number;
  readonly paths: GosaiPaths;
  /** The Python project with the driver bridge. Drivers are off without it. */
  readonly pythonDir?: string;
  /**
   * Why the desktop app could not install the Python runtime. Python drivers
   * are then unavailable, and their calls fail with this reason.
   */
  readonly pythonSetupError?: string;
  /** uv, for the Python environments of apps that ship drivers. Defaults to `uv` on PATH. */
  readonly uv?: string;
  /** uv's cache for those environments. uv's default cache when omitted. */
  readonly uvCacheDir?: string;
  readonly builtinAppsDir?: string;
  /** The built SDK (`index.js`, `host.js`, `app-host.js`), served under `/sdk/<version>/`. */
  readonly sdkDir?: string;
  /** False when Python is disabled (GOSAI_PYTHON=0). */
  readonly enablePython?: boolean;
  /**
   * Secret generated by desktop main at each launch. It authorizes the
   * dashboard, and app tokens are derived from it.
   */
  readonly dashboardToken: string;
  /** Extra origins allowed besides loopback http origins, e.g. `file://` and `null`. */
  readonly allowedOrigins?: readonly string[];
  /** Extra Host header names allowed besides loopback names and the bind host. */
  readonly allowedHosts?: readonly string[];
  /** Let `app:install` clone `file:` URLs. Only for tests. */
  readonly allowFileInstalls?: boolean;
}

export interface GosaiServer {
  stop(): Promise<void>;
  /** Actual bound port (differs from options.port when 0 was requested). */
  readonly port: number;
  readonly logger: Logger;
  readonly bus: EventBus;
  readonly drivers: DriverHub;
  readonly apps: AppManager;
  readonly monitor: SystemMonitor;
  readonly config: ConfigStore;
  readonly appSettings: AppSettingsStore;
  readonly storage: AppStorage;
}

export async function createServer(options: ServerOptions): Promise<GosaiServer> {
  const { paths } = options;
  const logger = new Logger({ logsDir: paths.logs });
  const log = logger.child('server');
  const bus = new EventBus({
    onListenerError: (err, event) =>
      log.error('event listener failed', { event, err: String(err) }),
  });
  logger.subscribe((entry) => bus.emit(ServerEvents.Log, entry, 'logger'));

  migrateLegacyAppData(paths, logger.child('migration'));

  const config = new ConfigStore(paths.config, bus, logger.child('config'));
  const deviceSettings = new AppSettingsStore(paths, bus, logger.child('app-config'));

  // Without a Python environment no bridge starts, and driver calls fail with the reason.
  const pythonUnavailable = pythonUnavailableReason(options);
  const python: PythonToolchain | undefined =
    pythonUnavailable === null && options.pythonDir
      ? {
          pythonDir: options.pythonDir,
          uv: options.uv ?? 'uv',
          ...(options.uvCacheDir ? { uvCacheDir: options.uvCacheDir } : {}),
        }
      : undefined;
  const drivers = new DriverHub({
    pythonDir: options.pythonDir ?? '',
    logger,
    bus,
    getDriverConfig: (binding, driver) =>
      driverConfigFor({ config, appSettings: deviceSettings }, binding, driver),
    ...(python ? { apps: pythonAppBridges({ toolchain: python, paths, logger }) } : {}),
    ...(pythonUnavailable !== null ? { unavailable: pythonUnavailable } : {}),
  });
  if (pythonUnavailable === null) {
    try {
      await drivers.start();
    } catch (err) {
      log.warn('failed to start python bridge', { err: String(err) });
    }
  } else if (options.enablePython === false) {
    log.info('python drivers are disabled');
  } else {
    log.warn('python drivers are unavailable', { reason: pythonUnavailable });
  }

  const apps = new AppManager({
    paths,
    logger,
    bus,
    drivers,
    appDrivers: drivers,
    ...(python ? { python } : {}),
    ...(options.builtinAppsDir ? { builtinAppsDir: options.builtinAppsDir } : {}),
    allowFileInstalls: options.allowFileInstalls === true,
  });
  const storage = new AppStorage(paths);
  const settings = new AppSettingsValuesStore(apps, storage, bus);
  const calibration = new CalibrationStore({
    getManifest: (slug) => apps.getManifest(slug),
    storage,
    logger: logger.child('calibration'),
    onChanged: (appSlug, { calibrated }) =>
      bus.emit(ServerEvents.CalibrationChanged, { appSlug, calibrated }, 'calibration'),
  });

  const monitor = new SystemMonitor({
    bus,
    logger: logger.child('monitor'),
    pythonUnavailable: () => drivers.unavailableReason(),
  });
  monitor.start();

  const gateway = new WebSocketGateway(bus, logger.child('ipc'), {
    serverVersion: SERVER_VERSION,
    handlers: createCommandHandlers({
      apps,
      drivers,
      config,
      deviceSettings,
      settings,
      storage,
      calibration,
      logger,
      bus,
    }),
    onClientDisconnect: (clientId) => drivers.unsubscribeAll(clientId),
  });

  let boundPort = options.port;
  const guard = new RequestGuard({
    bindHost: options.host,
    port: () => boundPort,
    ...(options.allowedHosts ? { allowedHosts: options.allowedHosts } : {}),
    ...(options.allowedOrigins ? { allowedOrigins: options.allowedOrigins } : {}),
  });
  const authenticate = (req: Request, token: string | null = null): TokenScope | null =>
    verifyToken(options.dashboardToken, token ?? readBearerToken(req));

  const routes = createHttpRoutes({
    apps,
    guard,
    authenticate,
    ...(options.sdkDir ? { sdkDir: options.sdkDir } : {}),
  });

  let server: ReturnType<typeof Bun.serve<ClientData>>;
  try {
    server = Bun.serve<ClientData>({
      hostname: options.host,
      port: options.port,
      fetch(req, srv) {
        const rejected = guard.reject(req);
        if (rejected) return rejected;
        const url = new URL(req.url);
        if (url.pathname === '/ws') {
          // Browsers can't set headers on a WebSocket, so the token may come
          // in the query string.
          const scope = authenticate(req, url.searchParams.get('token'));
          if (!scope) return new Response('Unauthorized', { status: 401 });
          const denial = appOriginDenial(req, scope);
          if (denial) return new Response(denial, { status: 403 });
          const grant = grantFor(scope, (slug) => apps.grantedCapabilities(slug));
          const data: ClientData = { clientId: crypto.randomUUID(), grant };
          if (srv.upgrade(req, { data })) return undefined;
          return new Response('Upgrade failed', { status: 426 });
        }
        return routes.fetch(req);
      },
      websocket: {
        open: (ws) => gateway.onOpen(ws),
        close: (ws) => gateway.onClose(ws),
        message: (ws, msg) => gateway.onMessage(ws, msg),
      },
    });
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    if (message.includes('EADDRINUSE') || message.includes('Address already in use')) {
      log.error('port already in use', { port: options.port, host: options.host });
      throw new Error(
        `GOSAI cannot bind to ${options.host}:${options.port} - the port is already in use. ` +
          'Stop the other process or set GOSAI_PORT to a free port.',
      );
    }
    throw err;
  }

  boundPort = server.port ?? options.port;
  log.info(`gosai server up on http://${options.host}:${boundPort}`);

  // Drivers can take minutes to start, so the server doesn't wait.
  void apps.autoStart(config.get().autoStartApps);

  return {
    port: boundPort,
    logger,
    bus,
    drivers,
    apps,
    monitor,
    config,
    appSettings: deviceSettings,
    storage,
    async stop() {
      log.info('shutting down');
      monitor.stop();
      gateway.close();
      await apps.shutdown();
      try {
        await drivers.stop();
      } catch (err) {
        log.warn('drivers shutdown error', { err: String(err) });
      }
      await server.stop();
      await logger.flush();
    },
  };
}

/** Why Python drivers can't run, or null when the built-in bridge can start. */
function pythonUnavailableReason(options: ServerOptions): string | null {
  if (options.enablePython === false) return 'Python is disabled (GOSAI_PYTHON=0)';
  if (options.pythonSetupError) {
    return `the Python runtime could not be installed: ${options.pythonSetupError}`;
  }
  if (!options.pythonDir) return 'no Python project is configured';
  if (!existsSync(bridgeExecutable(options.pythonDir))) {
    const venv = join(options.pythonDir, '.venv');
    return existsSync(venv)
      ? `the Python environment ${venv} has no gosai-bridge; run \`uv sync\` in ${options.pythonDir}`
      : `there is no Python environment at ${venv}; run \`uv sync\` in ${options.pythonDir}`;
  }
  return null;
}
