/**
 * Wires the server together: stores, managers, the WebSocket gateway and the
 * HTTP routes. Paths come in through the options; see index.ts.
 */

import { existsSync } from 'node:fs';
import { join } from 'node:path';
import { verifyToken, type TokenScope } from '@gosai/shared/auth';
import { ServerEvents } from '@gosai/shared/events';
import { grantFor } from './access/capabilities.js';
import { readBearerToken, RequestGuard } from './access/request-guard.js';
import { migrateLegacyAppData } from './apps/data-migration.js';
import { AppManager } from './apps/manager.js';
import { AppSettingsValuesStore } from './apps/settings.js';
import { AppStorage } from './apps/storage.js';
import { createCommandHandlers } from './commands/index.js';
import { AppSettingsStore } from './config/app-settings.js';
import { ConfigStore } from './config/config.js';
import { driverConfigFor } from './drivers/camera-config.js';
import { DriverManager } from './drivers/manager.js';
import { createHttpRoutes } from './http/routes.js';
import { EventBus } from './ipc/bus.js';
import { WebSocketGateway, type ClientData } from './ipc/gateway.js';
import { Logger } from './logger/logger.js';
import { SystemMonitor } from './monitor/monitor.js';
import type { GosaiPaths } from './paths.js';
import { SERVER_VERSION } from './version.js';

export interface ServerOptions {
  readonly host: string;
  readonly port: number;
  readonly paths: GosaiPaths;
  /** The Python project with the driver bridge. Drivers are off without it. */
  readonly pythonDir?: string;
  readonly builtinAppsDir?: string;
  /** The built SDK bundle served at `/sdk-runtime.js`. */
  readonly sdkRuntimePath?: string;
  readonly enablePython?: boolean;
  /**
   * Secret generated by desktop main at each launch. It authorizes the
   * dashboard, and app tokens are derived from it.
   */
  readonly dashboardToken: string;
  /** Extra origins allowed besides loopback http origins, e.g. `file://` and `null`. */
  readonly allowedOrigins?: readonly string[];
  /** Extra Host header names allowed besides loopback names and the bind host. */
  readonly allowedHosts?: readonly string[];
  /** Let `app:install` clone `file:` URLs. Only for tests. */
  readonly allowFileInstalls?: boolean;
}

export interface GosaiServer {
  stop(): Promise<void>;
  /** Actual bound port (differs from options.port when 0 was requested). */
  readonly port: number;
  readonly logger: Logger;
  readonly bus: EventBus;
  readonly drivers: DriverManager;
  readonly apps: AppManager;
  readonly monitor: SystemMonitor;
  readonly config: ConfigStore;
  readonly appSettings: AppSettingsStore;
  readonly storage: AppStorage;
}

export async function createServer(options: ServerOptions): Promise<GosaiServer> {
  const { paths } = options;
  const logger = new Logger({ logsDir: paths.logs });
  const log = logger.child('server');
  const bus = new EventBus({
    onListenerError: (err, event) =>
      log.error('event listener failed', { event, err: String(err) }),
  });
  logger.subscribe((entry) => bus.emit(ServerEvents.Log, entry, 'logger'));

  migrateLegacyAppData(paths, logger.child('migration'));

  const config = new ConfigStore(paths.config, bus, logger.child('config'));
  const deviceSettings = new AppSettingsStore(paths, bus, logger.child('app-config'));

  const drivers = new DriverManager({
    pythonDir: options.pythonDir ?? '',
    logger,
    bus,
    getDriverConfig: (binding, driver) =>
      driverConfigFor({ config, appSettings: deviceSettings }, binding, driver),
  });
  if (options.enablePython !== false && options.pythonDir && hasBridge(options.pythonDir)) {
    try {
      await drivers.start();
    } catch (err) {
      log.warn('failed to start python bridge', { err: String(err) });
    }
  } else {
    log.info('python bridge disabled or unavailable', { pythonDir: options.pythonDir });
  }

  const apps = new AppManager({
    paths,
    logger,
    bus,
    drivers,
    ...(options.builtinAppsDir ? { builtinAppsDir: options.builtinAppsDir } : {}),
    allowFileInstalls: options.allowFileInstalls === true,
  });
  const storage = new AppStorage(paths);
  const settings = new AppSettingsValuesStore(apps, storage, bus);

  const monitor = new SystemMonitor({ bus, logger: logger.child('monitor') });
  monitor.start();

  const gateway = new WebSocketGateway(bus, logger.child('ipc'), {
    serverVersion: SERVER_VERSION,
    handlers: createCommandHandlers({
      apps,
      drivers,
      config,
      deviceSettings,
      settings,
      storage,
      logger,
      bus,
    }),
    onClientDisconnect: (clientId) => drivers.unsubscribeAll(clientId),
  });

  let boundPort = options.port;
  const guard = new RequestGuard({
    bindHost: options.host,
    port: () => boundPort,
    ...(options.allowedHosts ? { allowedHosts: options.allowedHosts } : {}),
    ...(options.allowedOrigins ? { allowedOrigins: options.allowedOrigins } : {}),
  });
  const authenticate = (req: Request, token: string | null = null): TokenScope | null =>
    verifyToken(options.dashboardToken, token ?? readBearerToken(req));

  const routes = createHttpRoutes({
    apps,
    guard,
    authenticate,
    ...(options.sdkRuntimePath ? { sdkRuntimePath: options.sdkRuntimePath } : {}),
  });

  let server: ReturnType<typeof Bun.serve<ClientData>>;
  try {
    server = Bun.serve<ClientData>({
      hostname: options.host,
      port: options.port,
      fetch(req, srv) {
        const rejected = guard.reject(req);
        if (rejected) return rejected;
        const url = new URL(req.url);
        if (url.pathname === '/ws') {
          // Browsers can't set headers on a WebSocket, so the token may come
          // in the query string.
          const scope = authenticate(req, url.searchParams.get('token'));
          if (!scope) return new Response('Unauthorized', { status: 401 });
          const grant = grantFor(scope, (slug) => apps.getManifest(slug)?.capabilities);
          const data: ClientData = { clientId: crypto.randomUUID(), grant };
          if (srv.upgrade(req, { data })) return undefined;
          return new Response('Upgrade failed', { status: 426 });
        }
        return routes.fetch(req);
      },
      websocket: {
        open: (ws) => gateway.onOpen(ws),
        close: (ws) => gateway.onClose(ws),
        message: (ws, msg) => gateway.onMessage(ws, msg),
      },
    });
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    if (message.includes('EADDRINUSE') || message.includes('Address already in use')) {
      log.error('port already in use', { port: options.port, host: options.host });
      throw new Error(
        `GOSAI cannot bind to ${options.host}:${options.port} - the port is already in use. ` +
          'Stop the other process or set GOSAI_PORT to a free port.',
      );
    }
    throw err;
  }

  boundPort = server.port ?? options.port;
  log.info(`gosai server up on http://${options.host}:${boundPort}`);

  // Drivers can take minutes to start, so the server doesn't wait.
  void apps.autoStart(config.get().autoStartApps);

  return {
    port: boundPort,
    logger,
    bus,
    drivers,
    apps,
    monitor,
    config,
    appSettings: deviceSettings,
    storage,
    async stop() {
      log.info('shutting down');
      monitor.stop();
      gateway.close();
      await apps.shutdown();
      try {
        await drivers.stop();
      } catch (err) {
        log.warn('drivers shutdown error', { err: String(err) });
      }
      await server.stop();
      await logger.flush();
    },
  };
}

function hasBridge(pythonDir: string): boolean {
  return existsSync(join(pythonDir, '.venv', 'bin', 'gosai-bridge'));
}
