/**
 * Generated by `bun run generate:protocol-types` (scripts/generate-protocol-types.ts)
 * from the zod schemas in protocol-schemas.ts. Do not edit.
 *
 * Plain types, so the client and the SDK's published declarations don't need zod.
 */

import type { Capability } from './capabilities.js';
import type {
  LogEntry,
  DriverSchemasResult,
  DriverInfo,
  InstalledApp,
  InvalidApp,
  RunningExperience,
  AppDeviceSettings,
  AppDeviceSettingsPatch,
  DeviceCatalog,
  GlobalConfig,
  GlobalConfigPatch,
  PerformanceSample,
  SystemStats,
} from './types.js';

/** What a client sends for each command. Fields with defaults may be left out. */
export interface CommandRequests {
  subscribe: {
    events: string[];
  };
  unsubscribe: {
    events: string[];
  };
  'system:ping': {
    [x: string]: never;
  };
  'apps:list': {
    [x: string]: never;
  };
  'app:install': {
    source: string;
    capabilities?: Capability[] | undefined;
    reuseData?: boolean | undefined;
  };
  'app:capabilities:set': {
    appSlug: string;
    capabilities: Capability[];
  };
  'app:uninstall': {
    slug: string;
    deleteData?: boolean | undefined;
  };
  'app:broadcast': {
    appSlug: string;
    topic: string;
    data?: unknown;
  };
  'app:log': {
    source: string;
    message: string;
    level?: 'error' | 'debug' | 'info' | 'warn' | undefined;
    data?: Record<string, unknown> | null | undefined;
  };
  'app:settings:get': {
    appSlug: string;
  };
  'app:settings:set': {
    appSlug: string;
    values: Record<string, string | number | boolean | null>;
  };
  'app:config:get': {
    appSlug: string;
  };
  'app:config:set': {
    appSlug: string;
    settings: AppDeviceSettingsPatch;
  };
  'experiences:list': {
    [x: string]: never;
  };
  'experience:start': {
    appSlug: string;
    experienceSlug: string;
    driverBinding?: string | undefined;
  };
  'experience:stop': {
    appSlug: string;
    experienceSlug: string;
  };
  'drivers:list': {
    [x: string]: never;
  };
  'drivers:schema': {
    driver?: string | undefined;
  };
  'devices:list': {
    [x: string]: never;
  };
  'driver:get-data': {
    event: string;
    driver: string;
    binding?: string | undefined;
  };
  'driver:execute': {
    action: string;
    driver: string;
    data?: unknown;
    binding?: string | undefined;
  };
  'driver:subscribe': {
    event: string;
    driver: string;
    binding?: string | undefined;
  };
  'driver:unsubscribe': {
    event: string;
    driver: string;
    binding?: string | undefined;
  };
  'logs:history': {
    limit?: number | undefined;
    level?: 'error' | 'debug' | 'info' | 'warn' | undefined;
  };
  'config:get': {
    [x: string]: never;
  };
  'config:set': GlobalConfigPatch;
  'storage:get': {
    appSlug: string;
    key: string;
  };
  'storage:set': {
    appSlug: string;
    key: string;
    value: unknown;
  };
  'storage:remove': {
    appSlug: string;
    key: string;
  };
  'storage:list': {
    appSlug: string;
  };
}

/** What the server hands each command handler, after validation. */
export interface ParsedCommandRequests {
  subscribe: {
    events: string[];
  };
  unsubscribe: {
    events: string[];
  };
  'system:ping': {
    [x: string]: never;
  };
  'apps:list': {
    [x: string]: never;
  };
  'app:install': {
    source: string;
    capabilities?: Capability[] | undefined;
    reuseData?: boolean | undefined;
  };
  'app:capabilities:set': {
    appSlug: string;
    capabilities: Capability[];
  };
  'app:uninstall': {
    slug: string;
    deleteData?: boolean | undefined;
  };
  'app:broadcast': {
    appSlug: string;
    topic: string;
    data?: unknown;
  };
  'app:log': {
    source: string;
    message: string;
    level?: 'error' | 'debug' | 'info' | 'warn' | undefined;
    data?: Record<string, unknown> | null | undefined;
  };
  'app:settings:get': {
    appSlug: string;
  };
  'app:settings:set': {
    appSlug: string;
    values: Record<string, string | number | boolean | null>;
  };
  'app:config:get': {
    appSlug: string;
  };
  'app:config:set': {
    appSlug: string;
    settings: AppDeviceSettingsPatch;
  };
  'experiences:list': {
    [x: string]: never;
  };
  'experience:start': {
    appSlug: string;
    experienceSlug: string;
    driverBinding?: string | undefined;
  };
  'experience:stop': {
    appSlug: string;
    experienceSlug: string;
  };
  'drivers:list': {
    [x: string]: never;
  };
  'drivers:schema': {
    driver?: string | undefined;
  };
  'devices:list': {
    [x: string]: never;
  };
  'driver:get-data': {
    event: string;
    driver: string;
    binding?: string | undefined;
  };
  'driver:execute': {
    action: string;
    driver: string;
    data?: unknown;
    binding?: string | undefined;
  };
  'driver:subscribe': {
    event: string;
    driver: string;
    binding?: string | undefined;
  };
  'driver:unsubscribe': {
    event: string;
    driver: string;
    binding?: string | undefined;
  };
  'logs:history': {
    limit?: number | undefined;
    level?: 'error' | 'debug' | 'info' | 'warn' | undefined;
  };
  'config:get': {
    [x: string]: never;
  };
  'config:set': GlobalConfigPatch;
  'storage:get': {
    appSlug: string;
    key: string;
  };
  'storage:set': {
    appSlug: string;
    key: string;
    value: unknown;
  };
  'storage:remove': {
    appSlug: string;
    key: string;
  };
  'storage:list': {
    appSlug: string;
  };
}

/** Each command's reply. */
export interface CommandResponses {
  subscribe: {
    ok: true;
  };
  unsubscribe: {
    ok: true;
  };
  'system:ping': {
    ts: number;
  };
  'apps:list': {
    apps: InstalledApp[];
    invalid: InvalidApp[];
  };
  'app:install': InstalledApp;
  'app:capabilities:set': InstalledApp;
  'app:uninstall': {
    slug: string;
    dataDeleted: boolean;
  };
  'app:broadcast': {
    ok: true;
  };
  'app:log': {
    ok: true;
  };
  'app:settings:get': {
    readonly [x: string]: unknown;
  };
  'app:settings:set': {
    readonly [x: string]: unknown;
  };
  'app:config:get': AppDeviceSettings;
  'app:config:set': AppDeviceSettings;
  'experiences:list': {
    experiences: RunningExperience[];
  };
  'experience:start': RunningExperience;
  'experience:stop': {
    ok: true;
  };
  'drivers:list': {
    drivers: DriverInfo[];
  };
  'drivers:schema': DriverSchemasResult;
  'devices:list': DeviceCatalog;
  'driver:get-data': unknown;
  'driver:execute': unknown;
  'driver:subscribe': {
    ok: true;
  };
  'driver:unsubscribe': {
    ok: true;
  };
  'logs:history': {
    logs: LogEntry[];
  };
  'config:get': GlobalConfig;
  'config:set': GlobalConfig;
  'storage:get':
    | {
        found: true;
        value: unknown;
      }
    | {
        found: false;
      };
  'storage:set': {
    ok: true;
  };
  'storage:remove': {
    removed: boolean;
  };
  'storage:list': {
    keys: string[];
  };
}

/** Payload of each event with a fixed name. */
export interface FixedEventPayloadMap {
  'server:welcome': {
    protocolVersion: number;
    serverVersion: string;
    clientId: string;
    capabilities: (
      | 'apps:read'
      | 'apps:manage'
      | 'experiences:read'
      | 'experiences:control'
      | 'drivers:read'
      | 'drivers:use'
      | 'devices:read'
      | 'config:read'
      | 'config:write'
      | 'app-config:read'
      | 'app-config:write'
      | 'storage:read'
      | 'storage:write'
      | 'app-events:use'
      | 'logs:read'
      | 'logs:write'
      | 'system:read'
      | 'events:wildcard'
    )[];
  };
  'server:log': LogEntry;
  'server:performance': PerformanceSample;
  'server:config-changed': GlobalConfig;
  'app:config-changed': {
    appSlug: string;
    settings: AppDeviceSettings;
  };
  'app:settings-changed': {
    appSlug: string;
    values: Readonly<Record<string, unknown>>;
  };
  'driver:state-changed': DriverInfo;
  'drivers:list-changed': {
    drivers: DriverInfo[];
  };
  'app:installed': InstalledApp;
  'app:uninstalled': {
    slug: string;
  };
  'apps:list-changed': {
    apps: InstalledApp[];
    invalid: InvalidApp[];
  };
  'experience:state-changed': RunningExperience;
  'experiences:list-changed': {
    experiences: RunningExperience[];
  };
  'system:stats': SystemStats;
}
