/**
 * Core type definitions shared across all GOSAI packages.
 */

import type { AppCalibrationSchema } from './calibration.js';
import type { Capability } from './capabilities.js';

export type LogLevel = 'debug' | 'info' | 'warn' | 'error';

export interface LogEntry {
  readonly timestamp: number;
  readonly level: LogLevel;
  readonly source: string;
  readonly message: string;
  readonly data?: Record<string, unknown>;
}

export type ExperienceState = 'idle' | 'starting' | 'running' | 'stopping' | 'crashed';
export type DriverState =
  'available' | 'starting' | 'running' | 'paused' | 'stopping' | 'stopped' | 'errored';
export type AppState = 'installed' | 'starting' | 'running' | 'stopping' | 'crashed';

export interface DriverRuntimeInfo {
  readonly backend: string;
  readonly provider?: string;
  readonly device?: string;
  readonly device_id?: number;
  readonly model?: string;
  readonly accelerated: boolean;
  readonly available_providers?: readonly string[];
  readonly requested_providers?: readonly string[];
  readonly reason?: string;
}

/** A JSON Schema object. */
export type JsonSchema = Readonly<Record<string, unknown>>;

/**
 * A driver's config, events and actions as JSON Schema, generated by the
 * Python bridge (`python -m gosai_py.schemas`). `$ref`s resolve against this
 * object's `$defs` only: names repeat across drivers with different contents.
 * `params` is null when an action takes no data.
 */
export interface DriverSchema {
  readonly $schema: string;
  readonly config: JsonSchema | null;
  readonly events: Readonly<
    Record<
      string,
      {
        readonly description: string;
        /**
         * How the bridge sends the event when Node reads slowly: only the newest
         * value, up to `queue_size` values dropping the oldest, or every value.
         */
        readonly delivery: 'latest' | 'buffered' | 'ordered';
        readonly queue_size?: number;
        readonly payload: JsonSchema;
      }
    >
  >;
  readonly actions: Readonly<
    Record<
      string,
      {
        readonly description: string;
        readonly params: JsonSchema | null;
        readonly result: JsonSchema;
        readonly requires_instance: boolean;
      }
    >
  >;
  readonly $defs: Readonly<Record<string, JsonSchema>>;
}

/** Response payload for `drivers:schema`, keyed by driver name. */
export interface DriverSchemasResult {
  readonly schemas: Readonly<
    Record<string, { readonly schemaVersion: string | null; readonly schema: DriverSchema | null }>
  >;
}

export interface DriverInfo {
  readonly name: string;
  readonly description?: string;
  readonly state: DriverState;
  readonly events: readonly string[];
  readonly actions: readonly string[];
  readonly dependencies: readonly string[];
  readonly subscribers: readonly string[];
  /**
   * Sharing policy. `false` (default) means the driver is exclusive: each app
   * binding gets its own device-bound instance. `true` means the driver can be
   * shared across apps (e.g. device-less utilities).
   */
  readonly shared: boolean;
  /** Runtime/backend information for the primary active instance, when known. */
  readonly runtime?: DriverRuntimeInfo;
  /** Running instances of this driver, keyed by binding/device. */
  readonly instances?: readonly DriverInstanceInfo[];
  /**
   * Hash of the driver's schema, when the bridge sends one. Fetch the schema
   * itself with `drivers:schema` and again when this changes.
   */
  readonly schemaVersion?: string;
}

/** A single running instance of a driver, bound to an app and/or device. */
export interface DriverInstanceInfo {
  /** Namespace the instance lives in: an app slug (exclusive) or `shared`/`shared:dev<n>`. */
  readonly instance: string;
  readonly state: DriverState;
  readonly subscribers: readonly string[];
  readonly runtime?: DriverRuntimeInfo;
}

export interface ExperienceDescriptor {
  readonly slug: string;
  readonly name: string;
  readonly description?: string;
  readonly entry: string;
  /**
   * Drivers kept running while the experience runs: built-in names such as
   * `hand_pose`, and app drivers named `<app slug>/<driver>`.
   */
  readonly drivers: readonly string[];
  readonly exclusive: boolean;
  readonly allowed?: readonly string[];
  readonly required?: readonly string[];
}

/**
 * Python drivers an app ships. They run in a bridge process of their own, in a
 * Python environment GOSAI builds for the app with uv, and are named
 * `<app slug>/<driver>`.
 */
export interface PythonConfig {
  /**
   * Package directory, relative to the app root, whose modules define the
   * drivers. Its name must be a Python identifier.
   */
  readonly drivers: string;
  /**
   * A requirements file, relative to the app root, installed into the app's
   * environment. Packages GOSAI's own environment has are pinned to its
   * versions.
   */
  readonly requirements?: string;
}

export interface AppManifest {
  readonly slug: string;
  readonly name: string;
  readonly description?: string;
  readonly version: string;
  /**
   * Versions of `@gosai/sdk` the app works with, as a semver range such as
   * `^0.1.0`. The server refuses to install the app, and lists it as invalid,
   * when the SDK it serves is outside the range.
   */
  readonly sdk?: string;
  readonly author?: string;
  readonly icon?: string;
  readonly experiences: readonly ExperienceDescriptor[];
  /**
   * Slug of the experience to launch when the user clicks the app card's
   * primary button. If omitted, the first experience in `experiences` is
   * used. Must reference an existing experience slug.
   */
  readonly default?: string;
  /** Python drivers the app ships. */
  readonly python?: PythonConfig;
  /**
   * Experiences to start when the server boots, for apps listed in
   * {@link GlobalConfig.autoStartApps}. Defaults to the default experience.
   */
  readonly startup?: readonly string[];
  /**
   * Capabilities the app asks for on top of the defaults every app gets. The
   * dashboard shows them at install time.
   */
  readonly capabilities?: readonly Capability[];
  /**
   * Device kinds this app needs. Drives the per-app device picker in the
   * dashboard. Omitted kinds default to `false`.
   */
  readonly requirements?: AppRequirements;
  /**
   * How the app is calibrated, when it needs calibration. Calibration is
   * explicit per app; it is not inferred from camera/display requirements.
   */
  readonly calibration?: AppCalibrationSchema;
  /**
   * Declarative settings schema. When present, the dashboard renders an
   * editable settings form for the app; values are persisted to the app's
   * key/value storage under {@link AppSettingsSchema.storageKey} as a single
   * (possibly nested) JSON object. `app:settings:get` returns it merged with
   * the declared defaults.
   */
  readonly settings?: AppSettingsSchema;
  /** Network access beyond the defaults the app window's security policy allows. */
  readonly network?: AppNetworkSchema;
}

/** Extra network access an app requests (see {@link AppManifest.network}). */
export interface AppNetworkSchema {
  /**
   * Origins the app's pages may connect to on top of their own origin and any
   * `https:` or `wss:` URL, as plain `scheme://host[:port]` strings with an
   * `http`, `https`, `ws` or `wss` scheme. For services on the local network,
   * such as `ws://relay.local:8080`.
   */
  readonly connect?: readonly string[];
}

/** Device kinds an app declares it needs, so the dashboard can offer pickers. */
export interface AppRequirements {
  readonly display?: boolean;
  readonly camera?: boolean;
  readonly microphone?: boolean;
  readonly speaker?: boolean;
}

/** Supported field input types for {@link AppSettingsField}. */
export type AppSettingsFieldType = 'boolean' | 'number' | 'string' | 'select';

/** A single editable setting. */
export interface AppSettingsField {
  /**
   * Dotted path into the stored config object (e.g. `"projection.mode"`).
   * Determines where the value is read/written within the storage object.
   */
  readonly key: string;
  readonly label: string;
  readonly type: AppSettingsFieldType;
  readonly description?: string;
  /** Default value, used when storage has no value for this key. */
  readonly default?: string | number | boolean;
  /** Options for `type: "select"`. */
  readonly options?: readonly AppSettingsOption[];
  /** Bounds/step for `type: "number"`. */
  readonly min?: number;
  readonly max?: number;
  readonly step?: number;
}

export interface AppSettingsOption {
  readonly value: string;
  readonly label: string;
}

/** A labelled group of related settings. */
export interface AppSettingsGroup {
  readonly label: string;
  readonly description?: string;
  readonly fields: readonly AppSettingsField[];
}

/** Declarative app settings schema (see {@link AppManifest.settings}). */
export interface AppSettingsSchema {
  /** Storage key the config object is persisted under. Defaults to `"config"`. */
  readonly storageKey?: string;
  readonly groups: readonly AppSettingsGroup[];
}

export interface InstalledApp {
  readonly manifest: AppManifest;
  readonly installedAt: number;
  /** `builtin` for apps shipped with GOSAI, `git` for installed ones. */
  readonly source: 'builtin' | 'git';
  /** True for apps shipped with GOSAI. They can't be uninstalled. */
  readonly builtin: boolean;
  /**
   * Requested capabilities the app's tokens hold: all of them for built-in
   * apps, the approved ones for installed apps.
   */
  readonly grantedCapabilities: readonly Capability[];
  readonly state: AppState;
}

/** An installed app whose manifest doesn't parse. The dashboard offers to uninstall it. */
export interface InvalidApp {
  readonly slug: string;
  readonly builtin: boolean;
  readonly error: string;
}

export interface RunningExperience {
  readonly appSlug: string;
  readonly experienceSlug: string;
  readonly state: ExperienceState;
  readonly startedAt: number;
}

export interface DisplayInfo {
  readonly id: number;
  readonly label: string;
  readonly bounds: { x: number; y: number; width: number; height: number };
  readonly workArea: { x: number; y: number; width: number; height: number };
  readonly scaleFactor: number;
  readonly primary: boolean;
  readonly internal: boolean;
}

export interface CameraSettings {
  readonly device: number;
  readonly width: number;
  readonly height: number;
  readonly fps: number;
  /** Clockwise software rotation applied once at capture, before all consumers. */
  readonly rotation?: 0 | 90 | 180 | 270;
}

/** One resolution and the frame rates that work at that size on the current device. */
export interface CameraFormat {
  readonly width: number;
  readonly height: number;
  readonly fps: readonly number[];
  readonly codecs?: readonly string[];
}

export interface CameraFormatsResult {
  readonly ok: boolean;
  readonly device: number;
  readonly formats?: readonly CameraFormat[];
  readonly error?: string;
}

export interface MicrophoneSettings {
  /** sounddevice input index, or null for the system default. */
  readonly device: number | null;
  readonly samplerate?: number;
  readonly channels?: number;
}

export interface SpeakerSettings {
  /** sounddevice output index, or null for the system default. */
  readonly device: number | null;
  readonly samplerate?: number;
}

export type DisplayMode = 'fullscreen' | 'windowed';

export interface AppDisplaySettings {
  /** Electron display id, or null to fall back to the global/primary display. */
  readonly id: number | null;
  readonly mode: DisplayMode;
}

/**
 * Per-application device overrides, persisted per app slug. Camera and
 * microphone are exclusive (each app binds its own device); speaker and display
 * may be shared across apps. A missing field inherits the global setting or the
 * system default.
 */
export interface AppDeviceSettings {
  readonly display?: Partial<AppDisplaySettings>;
  readonly camera?: Partial<CameraSettings>;
  readonly microphone?: Partial<MicrophoneSettings>;
  readonly speaker?: Partial<SpeakerSettings>;
}

/** Makes every field of `T` nullable, where `null` clears the stored override. */
export type Clearable<T> = { readonly [K in keyof T]?: T[K] | null };

/**
 * Patch for per-app device settings. Each block is shallow-merged over the
 * stored block. `null` for a block or a field removes that override.
 */
export interface AppDeviceSettingsPatch {
  readonly display?: Clearable<AppDisplaySettings> | null;
  readonly camera?: Clearable<CameraSettings> | null;
  readonly microphone?: Clearable<MicrophoneSettings> | null;
  readonly speaker?: Clearable<SpeakerSettings> | null;
}

/** A single enumerated hardware device offered to the per-app device picker. */
export interface DeviceOption {
  readonly index: number;
  readonly label: string;
  readonly isDefault?: boolean;
}

export interface DeviceCatalog {
  readonly cameras: readonly DeviceOption[];
  readonly microphones: readonly DeviceOption[];
  readonly speakers: readonly DeviceOption[];
}

export interface GlobalConfig {
  readonly displayId: number | null;
  /** Port a standalone server listens on when `GOSAI_PORT` isn't set. */
  readonly serverPort: number;
  /** Apps whose `startup` experiences start when the server boots. */
  readonly autoStartApps: readonly string[];
  readonly camera: CameraSettings;
}

/** Patch for {@link GlobalConfig}. `camera` is merged field by field. */
export interface GlobalConfigPatch {
  readonly displayId?: number | null;
  readonly serverPort?: number;
  readonly autoStartApps?: readonly string[];
  readonly camera?: Partial<CameraSettings>;
}

/** Values of an app's declared settings, nested by the dotted field keys. */
export type AppSettingsValues = Readonly<Record<string, unknown>>;

/** A declared setting's value. `null` in a patch restores the default. */
export type AppSettingValue = string | number | boolean;

/** A driver event routed to one binding, delivered as `driver:event:<binding>`. */
export interface DriverEventPayload {
  readonly driver: string;
  readonly event: string;
  readonly data: unknown;
  readonly ts: number;
  readonly binding: string;
}

export interface PerformanceSample {
  readonly source: string;
  /** Driver instance namespace, for driver samples. */
  readonly instance?: string;
  readonly type: 'driver' | 'experience' | 'app' | 'system';
  readonly metric: string;
  readonly value: number;
  readonly timestamp: number;
}

export interface SystemStats {
  readonly cpuPercent: number;
  readonly memoryBytes: number;
  readonly memoryTotalBytes: number;
  readonly uptimeMs: number;
}
